### Pandas Series
a Series is a one dimensional labeled array capable of holding any data type, the axis labelled are collectivey called the index

There are multiple ways to create a pandas series

In [3]:
pip install pandas

Requirement already satisfied: pandas in d:\datavisualization\pyhton\.venv\lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in d:\datavisualization\pyhton\.venv\lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\datavisualization\pyhton\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in d:\datavisualization\pyhton\.venv\lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in d:\datavisualization\pyhton\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import numpy as np
import pandas as pd

In [5]:
labels=['a','b','c']
my_list=[10,20,30]
my_arr=np.array([10,20,30])
d={1:10,2:20,3:30}

In [6]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

In [7]:
pd.Series(my_list,index=labels)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(my_arr)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(d)

1    10
2    20
3    30
dtype: int64

### DataFrames

Creating Dataframes

In [10]:
data={
    "Name":['John','Arna','Peter','Linda'],
    "Age":[24,34,23,42],
    "City":["New York","Paris","Berlin","London"],
    "Salary":[6500,70000,62000,85000]
}
# df=pd.DataFrame(data)
# print(df)
pd.DataFrame(data)

    Name  Age      City  Salary
0   John   24  New York    6500
1   Arna   34     Paris   70000
2  Peter   23    Berlin   62000
3  Linda   42    London   85000

In [11]:
data_list=[
    ['John',28,'NewYork',65000],
    ['Arna',34,'Paris',70000],
    ['Peter',32,'Berlin',62000],
    ['Linda',42,'London',85000]
]

pd.DataFrame(data_list)
column=["Name","Age","City","Salary"]
df2=pd.DataFrame(data_list,columns=column)
df2

    Name  Age     City  Salary
0   John   28  NewYork   65000
1   Arna   34    Paris   70000
2  Peter   32   Berlin   62000
3  Linda   42   London   85000

### Selection and Indexing of Columns

In [12]:
df2['Name']

0     John
1     Arna
2    Peter
3    Linda
Name: Name, dtype: str

In [13]:
df2[["Name","City"]]

    Name     City
0   John  NewYork
1   Arna    Paris
2  Peter   Berlin
3  Linda   London

### Creating a new Column

In [17]:
df2["Designation"]=["Doctor","Engineer","Doctor","Teacher"]
df2

    Name  Age     City  Salary Designation
0   John   28  NewYork   65000      Doctor
1   Arna   34    Paris   70000    Engineer
2  Peter   32   Berlin   62000      Doctor
3  Linda   42   London   85000     Teacher

### Remove a Column

In [18]:
# df2.drop('Designation',axis=1)
# df2.drop('Designation',axis=1,inplace=True)
df2

    Name  Age     City  Salary Designation
0   John   28  NewYork   65000      Doctor
1   Arna   34    Paris   70000    Engineer
2  Peter   32   Berlin   62000      Doctor
3  Linda   42   London   85000     Teacher

In [23]:
df2.drop(0,axis=0)

    Name  Age    City  Salary Designation
1   Arna   34   Paris   70000    Engineer
2  Peter   32  Berlin   62000      Doctor
3  Linda   42  London   85000     Teacher

#### Selecting a Row

In [25]:
df2

    Name  Age     City  Salary Designation
0   John   28  NewYork   65000      Doctor
1   Arna   34    Paris   70000    Engineer
2  Peter   32   Berlin   62000      Doctor
3  Linda   42   London   85000     Teacher

In [29]:
df2.loc[0]

Name              John
Age                 28
City           NewYork
Salary           65000
Designation     Doctor
Name: 0, dtype: object

In [28]:
df2.loc[[0,1]]

   Name  Age     City  Salary Designation
0  John   28  NewYork   65000      Doctor
1  Arna   34    Paris   70000    Engineer

#### Selecting Subset of Rows and Columns

In [30]:
df2.loc[[0,1]][['City','Salary']]

      City  Salary
0  NewYork   65000
1    Paris   70000

In [31]:
df2.loc[[2,3]][["Name","Age"]]

    Name  Age
2  Peter   32
3  Linda   42

#### Conditional Selection

In [32]:
df2

    Name  Age     City  Salary Designation
0   John   28  NewYork   65000      Doctor
1   Arna   34    Paris   70000    Engineer
2  Peter   32   Berlin   62000      Doctor
3  Linda   42   London   85000     Teacher

In [33]:
# only want to see those people wholse age is above 30
df2[df2["Age"]>30]

    Name  Age    City  Salary Designation
1   Arna   34   Paris   70000    Engineer
2  Peter   32  Berlin   62000      Doctor
3  Linda   42  London   85000     Teacher

In [35]:
# only want people  whose age is above 30 and their city must be paris
df2[(df2["Age"]>30) & (df2["City"]=="Paris")]

   Name  Age   City  Salary Designation
1  Arna   34  Paris   70000    Engineer

#### Finding Missing Data

In [55]:
data={
    'A':[1,2,np.nan,4,5],
    'B':[1,2,3,4,5],
    'C':[1,2,3,np.nan,np.nan],
    'D':[1,np.nan,np.nan,np.nan,5],
}
df3=pd.DataFrame(data)
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [56]:
df3.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [57]:
df3.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

#### Removing Missing Data

In [58]:
# Works on the basis of Row
df3.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [59]:
df3.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

##### Fill Missing Values with zero

In [60]:
df3.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [61]:
df3

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

#### Fill different values for each column

In [62]:
values={'A':0,'B':100,'C':300,'D':400}
df3.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  400.0
2  0.0  3    3.0  400.0
3  4.0  4  300.0  400.0
4  5.0  5  300.0    5.0

Fill With Mean

In [64]:
df3.fillna(df3.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0