In [5]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

print("Everything is working 👍🏻")

Everything is working 👍🏻

In [6]:
df=pd.read_csv('SuperMarketAnalysis.csv')

In [7]:
df.shape

(1000, 17)

In [8]:
df.head(10)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
8,665-32-9167,Alex,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,1/10/2019,5:15:00 PM,Credit card,72.52,4.761905,3.6260,7.2
9,692-92-5582,Cairo,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,2/20/2019,1:27:00 PM,Credit card,164.52,4.761905,8.2260,5.9

In [9]:
df.tail(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

name of all columns

In [10]:
df.columns

Index(['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender',
       'Product line', 'Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Date',
       'Time', 'Payment', 'cogs', 'gross margin percentage', 'gross income',
       'Rating'],
      dtype='str')

find data type of each columns

In [11]:
df.dtypes

Invoice ID                     str
Branch                         str
City                           str
Customer type                  str
Gender                         str
Product line                   str
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Sales                      float64
Date                           str
Time                           str
Payment                        str
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

check whether there is any missin value
sum() will give column wise

In [12]:
# print(df.isna().sum())
print(df.isna().sum().sum())

0

number of unique values in each columns

In [13]:
df.nunique()

Invoice ID                 1000
Branch                        3
City                          3
Customer type                 2
Gender                        2
Product line                  6
Unit price                  943
Quantity                     10
Tax 5%                      990
Sales                       990
Date                         89
Time                        506
Payment                       3
cogs                        990
gross margin percentage       1
gross income                990
Rating                       61
dtype: int64

nu,ber of unique cities

In [14]:
df['City'].nunique()

3

number of unique product pines

In [15]:
df['Product line'].nunique()

6

number of unique payment modes

In [16]:
df['Payment'].nunique()

3

how many transactions came form each city

In [17]:
df['City'].value_counts()

City
Yangon       340
Mandalay     332
Naypyitaw    328
Name: count, dtype: int64

how many transactions from each branch

In [18]:
df['Branch'].value_counts()

Branch
Alex     340
Cairo    332
Giza     328
Name: count, dtype: int64

from each customer type

In [19]:
df['Customer type'].value_counts()

Customer type
Member    565
Normal    435
Name: count, dtype: int64

made by each gender

In [20]:
df['Gender'].value_counts()

Gender
Female    571
Male      429
Name: count, dtype: int64

belongs to each product line

In [21]:
df['Product line'].value_counts()

Product line
Fashion accessories       178
Food and beverages        174
Electronic accessories    170
Sports and travel         166
Home and lifestyle        160
Health and beauty         152
Name: count, dtype: int64

how many transactiosn use each payment method

In [22]:
df['Payment'].value_counts()

Payment
Ewallet        345
Cash           344
Credit card    311
Name: count, dtype: int64

which product line has the most transaction

In [23]:
df['Product line'].value_counts().idxmax()

'Fashion accessories'

Which payment method was used most

In [24]:
df['Payment'].value_counts().idxmax()

'Ewallet'

Which city has most transaction

In [25]:
df['City'].value_counts().idxmax()

'Yangon'

which customer appears most

In [26]:
df['Customer type'].value_counts().idxmax()

'Member'

What is the average unit price

In [27]:
print(df['Unit price'].mean())

55.67213

what is the average quatity purchase

In [28]:
print(df['Quantity'].mean())

5.51

avergae total sales amount

In [29]:
print(df['Sales'].mean())

322.966749

maximum total sale

In [30]:
print(df['Sales'].max())

1042.65

minimum total sale

In [31]:
print(df['Sales'].min())

10.6785

total revenue

In [32]:
print(df['Sales'].sum())

322966.749

total gross income

In [33]:
print(df['gross income'].sum())

15379.368999999999

highest rated transaction

In [34]:
print(df['Rating'].max())

10.0

average customer rating

In [35]:
print(df['Rating'].mean())

6.9727

total quatity of products sold

In [36]:
print(df['Quantity'].sum())

5510

Find all transactions where

qunatity is greater than 5

In [37]:
df[df['Quantity']>7]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.288,489.048,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.288,8.4
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.780,772.380,2/24/2019,11:38:00 AM,Ewallet,735.60,4.761905,36.780,8.0
13,252-56-2699,Alex,Yangon,Member,Female,Food and beverages,43.19,10,21.595,453.495,2/7/2019,4:48:00 PM,Ewallet,431.90,4.761905,21.595,8.2
14,829-34-3910,Alex,Yangon,Member,Female,Health and beauty,71.38,10,35.690,749.490,3/29/2019,7:21:00 PM,Cash,713.80,4.761905,35.690,5.7
25,227-03-5010,Alex,Yangon,Member,Female,Home and lifestyle,52.59,8,21.036,441.756,3/22/2019,7:20:00 PM,Credit card,420.72,4.761905,21.036,8.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.170,864.570,3/29/2019,7:12:00 PM,Ewallet,823.40,4.761905,41.170,4.3
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.148,633.108,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.148,8.4
991,602-16-6955,Cairo,Mandalay,Normal,Female,Sports and travel,76.60,10,38.300,804.300,1/24/2019,6:10:00 PM,Ewallet,766.00,4.761905,38.300,6.0
993,690-01-6631,Cairo,Mandalay,Normal,Male,Fashion accessories,17.49,10,8.745,183.645,2/22/2019,6:35:00 PM,Ewallet,174.90,4.761905,8.745,6.6
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.690,1022.490,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.690,4.4

total is greater than 500

In [38]:
df[df['Sales']>500]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
14,829-34-3910,Alex,Yangon,Member,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,7:21:00 PM,Cash,713.80,4.761905,35.6900,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,7:12:00 PM,Ewallet,823.40,4.761905,41.1700,4.3
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4
991,602-16-6955,Cairo,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,1/24/2019,6:10:00 PM,Ewallet,766.00,4.761905,38.3000,6.0
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

from YanGon

In [39]:
df.loc[df['City']=='Yangon']

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
990,886-18-2897,Alex,Yangon,Normal,Female,Food and beverages,56.56,5,14.1400,296.9400,3/22/2019,7:06:00 PM,Credit card,282.80,4.761905,14.1400,4.5
992,745-74-0715,Alex,Yangon,Normal,Male,Electronic accessories,58.03,2,5.8030,121.8630,3/10/2019,8:46:00 PM,Ewallet,116.06,4.761905,5.8030,8.8
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

made by members

In [40]:
df.loc[df['Customer type']=='Member']

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,7:12:00 PM,Ewallet,823.40,4.761905,41.1700,4.3
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4
994,652-49-6720,Giza,Naypyitaw,Member,Female,Electronic accessories,60.95,1,3.0475,63.9975,2/18/2019,11:40:00 AM,Ewallet,60.95,4.761905,3.0475,5.9
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

payment methos is ewallet

In [41]:
df.loc[df['Payment']=='Ewallet']

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
992,745-74-0715,Alex,Yangon,Normal,Male,Electronic accessories,58.03,2,5.8030,121.8630,3/10/2019,8:46:00 PM,Ewallet,116.06,4.761905,5.8030,8.8
993,690-01-6631,Cairo,Mandalay,Normal,Male,Fashion accessories,17.49,10,8.7450,183.6450,2/22/2019,6:35:00 PM,Ewallet,174.90,4.761905,8.7450,6.6
994,652-49-6720,Giza,Naypyitaw,Member,Female,Electronic accessories,60.95,1,3.0475,63.9975,2/18/2019,11:40:00 AM,Ewallet,60.95,4.761905,3.0475,5.9
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4

from food and beverage product line

In [42]:
df.loc[df['Product line']=="Food and beverages"]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
9,692-92-5582,Cairo,Mandalay,Member,Female,Food and beverages,54.84,3,8.2260,172.7460,2/20/2019,1:27:00 PM,Credit card,164.52,4.761905,8.2260,5.9
13,252-56-2699,Alex,Yangon,Member,Female,Food and beverages,43.19,10,21.5950,453.4950,2/7/2019,4:48:00 PM,Ewallet,431.90,4.761905,21.5950,8.2
18,329-62-1586,Alex,Yangon,Member,Female,Food and beverages,54.67,3,8.2005,172.2105,1/21/2019,6:00:00 PM,Credit card,164.01,4.761905,8.2005,8.6
28,145-94-9061,Cairo,Mandalay,Member,Female,Food and beverages,88.36,5,22.0900,463.8900,1/25/2019,7:48:00 PM,Cash,441.80,4.761905,22.0900,9.6
34,183-56-6882,Giza,Naypyitaw,Member,Female,Food and beverages,99.42,4,19.8840,417.5640,2/6/2019,10:42:00 AM,Ewallet,397.68,4.761905,19.8840,7.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
977,518-71-6847,Cairo,Mandalay,Member,Male,Food and beverages,26.60,6,7.9800,167.5800,2/26/2019,3:10:00 PM,Ewallet,159.60,4.761905,7.9800,4.9
979,151-33-7434,Cairo,Mandalay,Normal,Female,Food and beverages,67.77,1,3.3885,71.1585,2/4/2019,8:43:00 PM,Credit card,67.77,4.761905,3.3885,6.5
980,728-47-9078,Giza,Naypyitaw,Member,Male,Food and beverages,59.59,4,11.9180,250.2780,1/19/2019,12:46:00 PM,Cash,238.36,4.761905,11.9180,9.8
990,886-18-2897,Alex,Yangon,Normal,Female,Food and beverages,56.56,5,14.1400,296.9400,3/22/2019,7:06:00 PM,Credit card,282.80,4.761905,14.1400,4.5
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7

rating is greater than 8

In [43]:
df.loc[df['Rating']>8]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
13,252-56-2699,Alex,Yangon,Member,Female,Food and beverages,43.19,10,21.5950,453.4950,2/7/2019,4:48:00 PM,Ewallet,431.90,4.761905,21.5950,8.2
18,329-62-1586,Alex,Yangon,Member,Female,Food and beverages,54.67,3,8.2005,172.2105,1/21/2019,6:00:00 PM,Credit card,164.01,4.761905,8.2005,8.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
980,728-47-9078,Giza,Naypyitaw,Member,Male,Food and beverages,59.59,4,11.9180,250.2780,1/19/2019,12:46:00 PM,Cash,238.36,4.761905,11.9180,9.8
981,809-46-1866,Alex,Yangon,Normal,Male,Health and beauty,58.15,4,11.6300,244.2300,1/23/2019,5:44:00 PM,Cash,232.60,4.761905,11.6300,8.4
985,374-38-5555,Cairo,Mandalay,Normal,Female,Fashion accessories,63.71,5,15.9275,334.4775,2/7/2019,7:30:00 PM,Ewallet,318.55,4.761905,15.9275,8.5
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4
992,745-74-0715,Alex,Yangon,Normal,Male,Electronic accessories,58.03,2,5.8030,121.8630,3/10/2019,8:46:00 PM,Ewallet,116.06,4.761905,5.8030,8.8

quatity is greater than 5 and total is greter than 500

In [44]:
df.loc[(df['Quantity']>5) & (df['Sales']>500)]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
5,699-14-3026,Giza,Naypyitaw,Member,Female,Electronic accessories,85.39,7,29.8865,627.6165,3/25/2019,6:30:00 PM,Ewallet,597.73,4.761905,29.8865,4.1
7,315-22-5665,Giza,Naypyitaw,Member,Female,Home and lifestyle,73.56,10,36.7800,772.3800,2/24/2019,11:38:00 AM,Ewallet,735.60,4.761905,36.7800,8.0
14,829-34-3910,Alex,Yangon,Member,Female,Health and beauty,71.38,10,35.6900,749.4900,3/29/2019,7:21:00 PM,Cash,713.80,4.761905,35.6900,5.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
988,267-62-7380,Giza,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.1700,864.5700,3/29/2019,7:12:00 PM,Ewallet,823.40,4.761905,41.1700,4.3
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4
991,602-16-6955,Cairo,Mandalay,Normal,Female,Sports and travel,76.60,10,38.3000,804.3000,1/24/2019,6:10:00 PM,Ewallet,766.00,4.761905,38.3000,6.0
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

from yangon where customer is member

In [45]:
df.loc[(df['City']=='Yangon') & (df['Customer type']=='Member')]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
6,355-53-5943,Alex,Yangon,Member,Female,Electronic accessories,68.84,6,20.6520,433.6920,2/25/2019,2:36:00 PM,Ewallet,413.04,4.761905,20.6520,5.8
8,665-32-9167,Alex,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,1/10/2019,5:15:00 PM,Credit card,72.52,4.761905,3.6260,7.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
961,324-92-3863,Alex,Yangon,Member,Male,Electronic accessories,20.89,2,2.0890,43.8690,2/5/2019,6:45:00 PM,Cash,41.78,4.761905,2.0890,9.8
967,195-06-0432,Alex,Yangon,Member,Male,Home and lifestyle,81.01,3,12.1515,255.1815,1/13/2019,12:55:00 PM,Credit card,243.03,4.761905,12.1515,9.3
982,139-32-4183,Alex,Yangon,Member,Female,Sports and travel,97.48,9,43.8660,921.1860,3/14/2019,2:19:00 PM,Ewallet,877.32,4.761905,43.8660,7.4
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

where the payment is credit card and rating is greter than 7

In [46]:
df.loc[(df['Payment']=='Credit card' ) & (df['Rating']>7)]

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
8,665-32-9167,Alex,Yangon,Member,Female,Health and beauty,36.26,2,3.6260,76.1460,1/10/2019,5:15:00 PM,Credit card,72.52,4.761905,3.6260,7.2
18,329-62-1586,Alex,Yangon,Member,Female,Food and beverages,54.67,3,8.2005,172.2105,1/21/2019,6:00:00 PM,Credit card,164.01,4.761905,8.2005,8.6
25,227-03-5010,Alex,Yangon,Member,Female,Home and lifestyle,52.59,8,21.0360,441.7560,3/22/2019,7:20:00 PM,Credit card,420.72,4.761905,21.0360,8.5
27,189-17-4241,Alex,Yangon,Member,Female,Fashion accessories,87.67,2,8.7670,184.1070,3/10/2019,12:17:00 PM,Credit card,175.34,4.761905,8.7670,7.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
962,593-08-5916,Alex,Yangon,Normal,Female,Fashion accessories,15.50,1,0.7750,16.2750,3/19/2019,3:23:00 PM,Credit card,15.50,4.761905,0.7750,7.4
967,195-06-0432,Alex,Yangon,Member,Male,Home and lifestyle,81.01,3,12.1515,255.1815,1/13/2019,12:55:00 PM,Credit card,243.03,4.761905,12.1515,9.3
969,214-30-2776,Cairo,Mandalay,Member,Female,Electronic accessories,34.49,5,8.6225,181.0725,3/11/2019,7:44:00 PM,Credit card,172.45,4.761905,8.6225,9.0
970,746-04-1077,Cairo,Mandalay,Member,Female,Food and beverages,84.63,10,42.3150,888.6150,1/1/2019,11:36:00 AM,Credit card,846.30,4.761905,42.3150,9.0
989,430-53-4718,Cairo,Mandalay,Member,Male,Health and beauty,75.37,8,30.1480,633.1080,1/28/2019,3:46:00 PM,Credit card,602.96,4.761905,30.1480,8.4

total sales for each city

In [47]:
df.groupby('City')['Sales'].sum()

City
Mandalay     106197.6720
Naypyitaw    110568.7065
Yangon       106200.3705
Name: Sales, dtype: float64

average sales for each city

In [48]:
df.groupby('City')['Sales'].mean()

City
Mandalay     319.872506
Naypyitaw    337.099715
Yangon       312.354031
Name: Sales, dtype: float64

total sales for each product line

In [49]:
df.groupby('Product line')['Sales'].sum()

Product line
Electronic accessories    54337.5315
Fashion accessories       54305.8950
Food and beverages        56144.8440
Health and beauty         49193.7390
Home and lifestyle        53861.9130
Sports and travel         55122.8265
Name: Sales, dtype: float64

average rating for each product line

In [50]:
df.groupby('Product line')['Rating'].mean()

Product line
Electronic accessories    6.924706
Fashion accessories       7.029213
Food and beverages        7.113218
Health and beauty         7.003289
Home and lifestyle        6.837500
Sports and travel         6.916265
Name: Rating, dtype: float64

total quatity sold for eadh produvt line

In [51]:
df.groupby('Product line')['Quantity'].sum()

Product line
Electronic accessories    971
Fashion accessories       902
Food and beverages        952
Health and beauty         854
Home and lifestyle        911
Sports and travel         920
Name: Quantity, dtype: int64

average unit price for each product line

In [52]:
df.groupby('Product line')['Unit price'].mean()
# df.head()

Product line
Electronic accessories    53.551588
Fashion accessories       57.153652
Food and beverages        56.008851
Health and beauty         54.854474
Home and lifestyle        55.316937
Sports and travel         56.993253
Name: Unit price, dtype: float64

total gross income of each branch

In [53]:
df.groupby('Branch')['gross income'].sum()

Branch
Alex     5057.1605
Cairo    5057.0320
Giza     5265.1765
Name: gross income, dtype: float64

total sales for each payment method

In [54]:
df.groupby('Payment')['Sales'].sum()

Payment
Cash           112206.570
Credit card    100767.072
Ewallet        109993.107
Name: Sales, dtype: float64

average sales for each each customer type

In [55]:
df.groupby('Customer type')['Sales'].mean()

Customer type
Member    335.742945
Normal    306.372379
Name: Sales, dtype: float64

city generated highest total sales

In [56]:
df.groupby('City')['Sales'].sum().idxmax()

'Naypyitaw'

product lien generated highest total sales

In [57]:
df.groupby('Product line')['Sales'].sum().idxmax()

'Food and beverages'

branch generated highest gross income

In [58]:
df.groupby('Branch')['gross income'].sum().idxmax()
# df.head()

'Giza'

produxt line has highest average rating

In [59]:
df.groupby('Product line')['Rating'].mean().idxmax()

'Food and beverages'

payment method generated highest total sales

In [60]:
df.groupby('Payment')['Sales'].sum().idxmax()

'Cash'

customer type has highest average transaction value

In [61]:
df.groupby('Customer type')['Sales'].mean().idxmax()
# df.head()

'Member'

product line solde the highest total quantity

In [62]:
df.groupby('Product line')['Quantity'].sum().idxmax()

'Electronic accessories'

In [63]:
df.head()

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3

total sales of each city and product line

In [64]:
df.groupby(['City','Product line'])['Sales'].sum()

City       Product line
Mandalay   Electronic accessories    17051.4435
           Fashion accessories       16413.3165
           Food and beverages        15214.8885
           Health and beauty         19980.6600
           Home and lifestyle        17549.1645
           Sports and travel         19988.1990
Naypyitaw  Electronic accessories    18968.9745
           Fashion accessories       21560.0700
           Food and beverages        23766.8550
           Health and beauty         16615.3260
           Home and lifestyle        13895.5530
           Sports and travel         15761.9280
Yangon     Electronic accessories    18317.1135
           Fashion accessories       16332.5085
           Food and beverages        17163.1005
           Health and beauty         12597.7530
           Home and lifestyle        22417.1955
           Sports and travel         19372.6995
Name: Sales, dtype: float64

average sales for each city adn product line

In [65]:
df.groupby(['City','Product line'])['Sales'].mean()

City       Product line
Mandalay   Electronic accessories    310.026245
           Fashion accessories       264.730911
           Food and beverages        304.297770
           Health and beauty         376.993585
           Home and lifestyle        350.983290
           Sports and travel         322.390306
Naypyitaw  Electronic accessories    344.890445
           Fashion accessories       331.693385
           Food and beverages        360.103864
           Health and beauty         319.525500
           Home and lifestyle        308.790067
           Sports and travel         350.265067
Yangon     Electronic accessories    305.285225
           Fashion accessories       320.245265
           Food and beverages        295.915526
           Health and beauty         268.037298
           Home and lifestyle        344.879931
           Sports and travel         328.350839
Name: Sales, dtype: float64

total quantity sold by each gender fro each product line

In [66]:
df.groupby(['Gender','Product line'])['Quantity'].sum()

Gender  Product line
Female  Electronic accessories    548
        Fashion accessories       586
        Food and beverages        568
        Health and beauty         425
        Home and lifestyle        561
        Sports and travel         600
Male    Electronic accessories    423
        Fashion accessories       316
        Food and beverages        384
        Health and beauty         429
        Home and lifestyle        350
        Sports and travel         320
Name: Quantity, dtype: int64

average rating for each customer type and gender

In [67]:
df.groupby(['Customer type','Gender'])['Rating'].mean()

Customer type  Gender
Member         Female    6.887079
               Male      6.968421
Normal         Female    7.080000
               Male      7.010455
Name: Rating, dtype: float64

total sales for each branch and payment mode

In [68]:
df.groupby(['Branch','Payment'])['Sales'].max()

Branch  Payment
Alex    Cash            932.337
        Credit card    1039.290
        Ewallet         951.825
Cairo   Cash            867.090
        Credit card    1022.385
        Ewallet        1022.490
Giza    Cash           1003.590
        Credit card    1042.650
        Ewallet        1034.460
Name: Sales, dtype: float64

avegare total sales of each city and customer type

In [69]:
df.groupby(['Customer type','City'])['Sales'].mean()

Customer type  City
Member         Mandalay     330.520276
               Naypyitaw    345.231015
               Yangon       331.030405
Normal         Mandalay     307.109285
               Naypyitaw    325.327534
               Yangon       288.697290
Name: Sales, dtype: float64

which city and product combination generate highest sales

In [70]:
df.groupby(['City','Product line'])['Sales'].sum().idxmax()

('Naypyitaw', 'Food and beverages')

total from highest to lowest

In [71]:
df.sort_values('Sales')

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
822,784-21-9238,Giza,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,10.6785,2/7/2019,2:15:00 PM,Cash,10.17,4.761905,0.5085,5.9
629,308-39-1707,Alex,Yangon,Normal,Female,Fashion accessories,12.09,1,0.6045,12.6945,1/26/2019,6:19:00 PM,Credit card,12.09,4.761905,0.6045,8.2
223,279-62-1445,Giza,Naypyitaw,Member,Female,Fashion accessories,12.54,1,0.6270,13.1670,2/21/2019,12:38:00 PM,Cash,12.54,4.761905,0.6270,8.2
443,192-98-7397,Giza,Naypyitaw,Normal,Male,Fashion accessories,12.78,1,0.6390,13.4190,1/8/2019,2:11:00 PM,Ewallet,12.78,4.761905,0.6390,9.5
402,236-86-3015,Giza,Naypyitaw,Member,Male,Home and lifestyle,13.98,1,0.6990,14.6790,2/4/2019,1:38:00 PM,Ewallet,13.98,4.761905,0.6990,9.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
699,751-41-9720,Giza,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.7500,1023.7500,1/12/2019,4:18:00 PM,Ewallet,975.00,4.761905,48.7500,8.0
557,283-26-5248,Giza,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.2600,1034.4600,1/30/2019,8:23:00 PM,Ewallet,985.20,4.761905,49.2600,4.5
167,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.4900,1039.2900,2/8/2019,4:20:00 PM,Credit card,989.80,4.761905,49.4900,8.7
350,860-79-0874,Giza,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.6500,1042.6500,2/15/2019,2:53:00 PM,Credit card,993.00,4.761905,49.6500,6.6

top 10 by total sales

In [72]:
df.sort_values('Sales',ascending=False).head(10)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
350,860-79-0874,Giza,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.650,1042.650,2/15/2019,2:53:00 PM,Credit card,993.0,4.761905,49.650,6.6
167,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.490,1039.290,2/8/2019,4:20:00 PM,Credit card,989.8,4.761905,49.490,8.7
557,283-26-5248,Giza,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.260,1034.460,1/30/2019,8:23:00 PM,Ewallet,985.2,4.761905,49.260,4.5
699,751-41-9720,Giza,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.750,1023.750,1/12/2019,4:18:00 PM,Ewallet,975.0,4.761905,48.750,8.0
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.690,1022.490,3/2/2019,5:16:00 PM,Ewallet,973.8,4.761905,48.690,4.4
792,744-16-7898,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.37,10,48.685,1022.385,1/15/2019,1:48:00 PM,Credit card,973.7,4.761905,48.685,4.9
422,271-88-8734,Giza,Naypyitaw,Member,Female,Fashion accessories,97.21,10,48.605,1020.705,2/8/2019,1:00:00 PM,Credit card,972.1,4.761905,48.605,8.7
166,234-65-2137,Giza,Naypyitaw,Normal,Male,Home and lifestyle,95.58,10,47.790,1003.590,1/16/2019,1:32:00 PM,Cash,955.8,4.761905,47.790,4.8
357,554-42-2417,Giza,Naypyitaw,Normal,Female,Sports and travel,95.44,10,47.720,1002.120,1/9/2019,1:45:00 PM,Cash,954.4,4.761905,47.720,5.2
429,325-77-6186,Alex,Yangon,Member,Female,Home and lifestyle,90.65,10,45.325,951.825,3/8/2019,10:53:00 AM,Ewallet,906.5,4.761905,45.325,7.3

bottm 10 by total sales

In [73]:
df.sort_values('Sales').head(10)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
822,784-21-9238,Giza,Naypyitaw,Member,Male,Sports and travel,10.17,1,0.5085,10.6785,2/7/2019,2:15:00 PM,Cash,10.17,4.761905,0.5085,5.9
629,308-39-1707,Alex,Yangon,Normal,Female,Fashion accessories,12.09,1,0.6045,12.6945,1/26/2019,6:19:00 PM,Credit card,12.09,4.761905,0.6045,8.2
223,279-62-1445,Giza,Naypyitaw,Member,Female,Fashion accessories,12.54,1,0.6270,13.1670,2/21/2019,12:38:00 PM,Cash,12.54,4.761905,0.6270,8.2
443,192-98-7397,Giza,Naypyitaw,Normal,Male,Fashion accessories,12.78,1,0.6390,13.4190,1/8/2019,2:11:00 PM,Ewallet,12.78,4.761905,0.6390,9.5
402,236-86-3015,Giza,Naypyitaw,Member,Male,Home and lifestyle,13.98,1,0.6990,14.6790,2/4/2019,1:38:00 PM,Ewallet,13.98,4.761905,0.6990,9.8
282,490-29-1201,Alex,Yangon,Normal,Female,Sports and travel,15.34,1,0.7670,16.1070,1/6/2019,11:09:00 AM,Cash,15.34,4.761905,0.7670,6.5
53,778-71-5554,Giza,Naypyitaw,Member,Female,Fashion accessories,15.43,1,0.7715,16.2015,1/25/2019,3:46:00 PM,Credit card,15.43,4.761905,0.7715,6.1
962,593-08-5916,Alex,Yangon,Normal,Female,Fashion accessories,15.50,1,0.7750,16.2750,3/19/2019,3:23:00 PM,Credit card,15.50,4.761905,0.7750,7.4
424,489-64-4354,Giza,Naypyitaw,Normal,Male,Fashion accessories,16.28,1,0.8140,17.0940,3/9/2019,3:36:00 PM,Cash,16.28,4.761905,0.8140,5.0
808,559-61-5987,Cairo,Mandalay,Normal,Female,Health and beauty,17.75,1,0.8875,18.6375,1/14/2019,10:38:00 AM,Cash,17.75,4.761905,0.8875,8.6

product line accorsing to total sales

In [74]:
df.groupby('Product line')['Sales'].sum().sort_values()

Product line
Health and beauty         49193.7390
Home and lifestyle        53861.9130
Fashion accessories       54305.8950
Electronic accessories    54337.5315
Sports and travel         55122.8265
Food and beverages        56144.8440
Name: Sales, dtype: float64

city accorsing to average sales

In [75]:
df.groupby('City')['Sales'].mean().sort_values()

City
Yangon       312.354031
Mandalay     319.872506
Naypyitaw    337.099715
Name: Sales, dtype: float64

top 5 transactions with gighest gross income

In [76]:
df.sort_values('gross income',ascending=False).head(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
350,860-79-0874,Giza,Naypyitaw,Member,Female,Fashion accessories,99.30,10,49.65,1042.65,2/15/2019,2:53:00 PM,Credit card,993.0,4.761905,49.65,6.6
167,687-47-8271,Alex,Yangon,Normal,Male,Fashion accessories,98.98,10,49.49,1039.29,2/8/2019,4:20:00 PM,Credit card,989.8,4.761905,49.49,8.7
557,283-26-5248,Giza,Naypyitaw,Member,Female,Food and beverages,98.52,10,49.26,1034.46,1/30/2019,8:23:00 PM,Ewallet,985.2,4.761905,49.26,4.5
699,751-41-9720,Giza,Naypyitaw,Normal,Male,Home and lifestyle,97.50,10,48.75,1023.75,1/12/2019,4:18:00 PM,Ewallet,975.0,4.761905,48.75,8.0
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.69,1022.49,3/2/2019,5:16:00 PM,Ewallet,973.8,4.761905,48.69,4.4

In [77]:
df['Date']=pd.to_datetime(df['Date'])

In [78]:
df['Date'].min()

Timestamp('2019-01-01 00:00:00')

In [79]:
df['Date'].max()

Timestamp('2019-03-30 00:00:00')

In [80]:
df['Month']=df['Date'].dt.month
df['Month']

0      1
1      3
2      3
3      1
4      2
      ..
995    1
996    3
997    2
998    2
999    2
Name: Month, Length: 1000, dtype: int32

In [81]:
df['Date'].value_counts()

Date
2019-02-07    20
2019-02-15    19
2019-03-02    18
2019-01-08    18
2019-03-14    18
              ..
2019-02-01     6
2019-01-04     6
2019-03-21     6
2019-02-21     6
2019-03-17     6
Name: count, Length: 89, dtype: int64

In [82]:
df.groupby('Date')['Sales'].sum()

Date
2019-01-01    4745.1810
2019-01-02    1945.5030
2019-01-03    2078.1285
2019-01-04    1623.6885
2019-01-05    3536.6835
                ...
2019-03-26    1962.5130
2019-03-27    2902.8195
2019-03-28    2229.4020
2019-03-29    4023.2430
2019-03-30    4487.0595
Name: Sales, Length: 89, dtype: float64

In [83]:
df.groupby('Date')['Sales'].sum().idxmax()

Timestamp('2019-03-09 00:00:00')

In [84]:
df.groupby('Date')['Sales'].mean()

Date
2019-01-01    395.431750
2019-01-02    243.187875
2019-01-03    259.766062
2019-01-04    270.614750
2019-01-05    294.723625
                 ...
2019-03-26    150.962538
2019-03-27    290.281950
2019-03-28    222.940200
2019-03-29    502.905375
2019-03-30    407.914500
Name: Sales, Length: 89, dtype: float64