In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv(r'./Data/Anime.csv')

In [3]:
df=df.head()
# df.head()

In [4]:
# make a new col for episode count
df.loc[1]['Title']

'Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473,707 members'

#### Feature Extraction

In [5]:
# make a new col for episode count
def extractEpisodes(txt):
    check=False
    data=""
    for i in txt:
        if i==")":
            return data
        if check==True:
            data= data+i
        if i=='(':
            check= True

In [6]:
df['Episodes']=df['Title'].apply(extractEpisodes)
df['Episodes']=df['Episodes'].str.replace(" eps","")
df

   Rank                                              Title  Score Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10       64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07       24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06       13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06       51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05       10

In [7]:
df.loc[0]['Episodes']
df['Episodes']=df['Episodes'].astype(int)
df

   Rank                                              Title  Score  Episodes
0     1  Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...   9.10        64
1     2  Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...   9.07        24
2     3  Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...   9.06        13
3     4  Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...   9.06        51
4     5  Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...   9.05        10

In [8]:
# Make a new column for time stamps
df.loc[0]['Title']

'Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr 2009 - Jul 20103,218,472 membersManga StoreVolume 1€4.58Preview'

In [9]:
def extractTimeStamps(txt):
    data=""
    for i in range(len(txt)):
        if txt[i]==')':
            for j in range (i+1,i+20):
                data+=txt[j]
            return data

# def extractTimeStamps(txt):
#     check=False
#     data=""
#     for i in txt:
#         if i==",":
#             return data
#         if check==True:
#             data=data+i
#         if i==')':
#             check=True

In [10]:
df['Time Stamps']=df['Title'].apply(extractTimeStamps)
# df['Title'].apply(extractTimeStamps)
df

,Rank,Title,Score,Episodes,Time Stamps
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019

In [11]:

def calculate_months(x):
    start, end = x.split(" - ")
    
    start = pd.to_datetime(start, format="%b %Y")
    end = pd.to_datetime(end, format="%b %Y")
    
    return (end.year - start.year) * 12 + (end.month - start.month) + 1

df["Total Months"] = df["Time Stamps"].apply(calculate_months)

In [12]:
df

,Rank,Title,Score,Episodes,Time Stamps,Total Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.10,64,Apr 2009 - Jul 2010,16
1,2,"Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...",9.07,24,Apr 2011 - Sep 2011,6
2,3,Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...,9.06,13,Oct 2022 - Dec 2022,3
3,4,"Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...",9.06,51,Apr 2015 - Mar 2016,12
4,5,Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...,9.05,10,Apr 2019 - Jul 2019,4

In [14]:
# which anime has the highest score
df[df['Score']==df['Score'].max()]

,Rank,Title,Score,Episodes,Time Stamps,Total Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,16

In [15]:
# to five highest scoring anime
df['Title'].head()

0    Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...
1    Steins;GateTV (24 eps)Apr 2011 - Sep 20112,473...
2    Bleach: Sennen Kessen-henTV (13 eps)Oct 2022 -...
3    Gintama°TV (51 eps)Apr 2015 - Mar 2016605,113 ...
4    Shingeki no Kyojin Season 3 Part 2TV (10 eps)A...
Name: Title, dtype: str

In [16]:
# highest episodes count
df[df['Episodes']==df['Episodes'].max()]

,Rank,Title,Score,Episodes,Time Stamps,Total Months
0,1,Fullmetal Alchemist: BrotherhoodTV (64 eps)Apr...,9.1,64,Apr 2009 - Jul 2010,16